export const SWITCH_ADD_MODE = "SWITCH_ADD_MODE";
export const ADD_TODO = "ADD_TODO";
export const SWITCH_CHANGE_MODE = "SWITCH_CHANGE_MODE";
export const REMOVE_TODO = "REMOVE_TODO";
export const TURN_CHANGE_MODAL = "TURN_CHANGE_MODAL";
export const ADD_VARIABLE_TODO = "ADD_VARIABLE_TODO";
export const CHANGE_TODO = "CHANGE_TODO";
